// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKxWRMbFIHBidJFlWZt_nZUyT17fu6b3k',
    appId: '1:515939083237:web:012ccc19f7fb3b6bba050c',
    messagingSenderId: '515939083237',
    projectId: 'antrian-donor-darah',
    authDomain: 'antrian-donor-darah.firebaseapp.com',
    storageBucket: 'antrian-donor-darah.firebasestorage.app',
    measurementId: 'G-JES1NCD5YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHyb-cPjHRffTHhyZerRkZ6-__7LCcOqA',
    appId: '1:515939083237:android:0ecbf22495af5c46ba050c',
    messagingSenderId: '515939083237',
    projectId: 'antrian-donor-darah',
    storageBucket: 'antrian-donor-darah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiSrGd8MPu4TIQWVcgca9spFo8p9X0nV8',
    appId: '1:515939083237:ios:a31f1bee04300a44ba050c',
    messagingSenderId: '515939083237',
    projectId: 'antrian-donor-darah',
    storageBucket: 'antrian-donor-darah.firebasestorage.app',
    iosBundleId: 'com.example.antrianDonorDarah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiSrGd8MPu4TIQWVcgca9spFo8p9X0nV8',
    appId: '1:515939083237:ios:a31f1bee04300a44ba050c',
    messagingSenderId: '515939083237',
    projectId: 'antrian-donor-darah',
    storageBucket: 'antrian-donor-darah.firebasestorage.app',
    iosBundleId: 'com.example.antrianDonorDarah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKxWRMbFIHBidJFlWZt_nZUyT17fu6b3k',
    appId: '1:515939083237:web:11b649923db581ddba050c',
    messagingSenderId: '515939083237',
    projectId: 'antrian-donor-darah',
    authDomain: 'antrian-donor-darah.firebaseapp.com',
    storageBucket: 'antrian-donor-darah.firebasestorage.app',
    measurementId: 'G-KCVQY4YH7T',
  );
}
